server:
  servlet:
    context-path: /Notes
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notesdb
    username: notes_user
    password: notes_user

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        ddl-auto: validate
      jdbc:
        time_zone: UTC
      
  flyway:
    enabled: true
    schemas: public
    locations: classpath:/db/migration
jwt:
  secret: jwtsecret
  expirationDateInMs: 18000000